### ISSUE TITLE
Missing documents

### ISSUE THREAD

**Issue by baneitixiaomai** [Len-Li/Adv3D#2]
Could you upload
`parser.add_argument("--obj_loca", type=str, default='/home/leheng.li/sim_opt/lift3d_1214/stylegan_gen_perc/sample_sem_optim/')`
and file **tools/attk_loca_importance_pixelcount.py**

**Comment by Len-Li** [comment]
Hi,

You can refer to our lift3d repo for this checkpoint. 
https://github.com/EnVision-Research/Lift3D
